CREATE TABLE `bookmarkTranscripts` (
	`id` text PRIMARY KEY NOT NULL,
	`bookmarkId` text NOT NULL,
	`provider` text NOT NULL,
	`providerItemId` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`statusMessage` text,
	`sourceAttachmentsStatus` text DEFAULT 'pending' NOT NULL,
	`selectedTrackId` text,
	`sourceLanguage` text,
	`sourceIsAutoGenerated` integer,
	`sourceTranscript` text,
	`text` text,
	`manualOverride` integer DEFAULT false NOT NULL,
	`revision` integer DEFAULT 0 NOT NULL,
	`sourceFingerprint` text,
	`sourceFetchedAt` integer,
	`createdAt` integer NOT NULL,
	`modifiedAt` integer,
	FOREIGN KEY (`bookmarkId`) REFERENCES `bookmarks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `bookmarkTranscripts_bookmarkId_idx` ON `bookmarkTranscripts` (`bookmarkId`);--> statement-breakpoint
CREATE INDEX `bookmarkTranscripts_providerItemId_idx` ON `bookmarkTranscripts` (`providerItemId`);--> statement-breakpoint
CREATE UNIQUE INDEX `bookmarkTranscripts_bookmark_provider_unique` ON `bookmarkTranscripts` (`bookmarkId`,`provider`);--> statement-breakpoint
ALTER TABLE `assets` ADD `transcriptId` text REFERENCES bookmarkTranscripts(id) ON DELETE cascade;--> statement-breakpoint
ALTER TABLE `bookmarks` ADD `summaryProvenance` text;--> statement-breakpoint
ALTER TABLE `bookmarks` ADD `summaryStale` integer DEFAULT false NOT NULL;
